// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yl9m5TqKrNKDyaytXGk7hOgNkkAbAj4',
    appId: '1:872052461203:android:24db28634b512fb7a84766',
    messagingSenderId: '872052461203',
    projectId: 'imake-vision',
    storageBucket: 'imake-vision.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV_HT30NbBPcbyYsvmy4PueEEcN8TC_L8',
    appId: '1:872052461203:ios:30fdbff759b3272ea84766',
    messagingSenderId: '872052461203',
    projectId: 'imake-vision',
    storageBucket: 'imake-vision.firebasestorage.app',
    androidClientId: '872052461203-dnqenvu2arhpdij4qabanopsemprfd0u.apps.googleusercontent.com',
    iosClientId: '872052461203-vupvdrfhldiloobt40s8d691h6gsrqgb.apps.googleusercontent.com',
    iosBundleId: 'com.imake.banchee',
  );
}
